#!/bin/bash
DIR="${BASH_SOURCE%/*}"

if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/railsPsqlFns"

usage () {
cat <<END
NAME
       $(basename $0)

       This program checks if Ruby, Ruby-on-Rails and NodeJS are
       installed on the user OS.

SYNOPSIS
       $(basename $0) [-h]

OPTIONS 
       -h: get help

REQUIREMENTS (Script)
       'okrails' requires the script 'railsPsqlFns', which should be in the same 
       directory as 'okpsql'. Both scrips should be on the user's path.

       It may be necessary to change user permissions. For example:

       chmod u+x "${HOME}/bin/okpsql"
       chmod u+x "${HOME}/bin/railsPsqlFns"

       It is recommended that the scripts are located in \$HOME/bin,
       or that softlinks are created from this directory to both filles. 
       
       For the last possibility, you may wish to execute the following from
       within \${HOME}/bin: 

       ln -s /path/to/okpsql okrails
       ln -s /path/to/railsPsqlFns railsPsqlFns

EXAMPLE USAGE
       okpsql
       okpsql "PSQL-ENV-VARIABLE"
END
}

## Set options
while getopts ":h" opt; do
	case $opt in
		h)
			usage | less
			exit 1
			;;
	esac
done
init () {
	for var in "node" "ruby" "rails"; do
		isProgramInstalled "${var}"
	done
} 
init
