#!/bin/bash

DIR="${BASH_SOURCE%/*}"

if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/okrails"
. "$DIR/okpsql"

# Functions
usage () {
cat <<END
NAME
       $(basename $0)


SYNOPSIS
       $(basename $0) [-h] [<password ENV variable name>]

DESCRIPTION


OPTIONS 
  
       -h: get help

REQUIREMENTS (Tests)

REQUIREMENTS (Script)

END
}

## Set options
while getopts ":h" opt; do
	case $opt in
		h)
			usage | less
			exit 1
			;;
	esac
done
init () {
	isPostgresInstalled
	verifyPostgresLogin "${@}"
	checkPostgresGem 
	isRubyInstalled
	isRailsInstalled 2>/dev/null 
}
init
